

-- --------------------------------------------------
--	Table structure for table  DEWEY
-- --------------------------------------------------

-- DROP TABLE IF EXISTS DEWEY;

CREATE TABLE DEWEY
(
  ID		IDENTITY PRIMARY KEY NOT NULL,
  OCCORENZE	INT DEFAULT 0 NOT NULL,
  NOME		VARCHAR(300) NOT NULL,
  NOMENORM	VARCHAR(300) NOT NULL,
  FULLNORM	VARCHAR(350) NOT NULL,
  CDD		VARCHAR(30) NOT NULL,
  CDDNORM	VARCHAR(30) NOT NULL,
  COD3		VARCHAR(3) NOT NULL
);


CALL FTL_CREATE_INDEX('PUBLIC', 'DEWEY', 'FULLNORM');
-- CALL FTL_DROP_INDEX('PUBLIC', 'DEWEY');


-- CALL FT_CREATE_INDEX('PUBLIC', 'DEWEY', 'FULLNORM');
-- CALL FT_DROP_INDEX('PUBLIC', 'DEWEY');
